[package]
name = "small-repl"
version = "0.1.0"
authors = ["AmiralBl3ndic <camille.briand@efrei.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
